### ISSUE TITLE
com.google.api.gax.rpc.InvalidArgumentException

### ISSUE THREAD

**Issue by aditya-protonn** [googleapis/java-video-transcoder#187]
Unable to get rid of this error. I was using google transcoder jar and faced this :

OS : Mac BigSur 11.1 (M1 chip)
Runtime : Java 11
SDK version :  'com.google.cloud:google-cloud-video-transcoder:0.2.0'

```
13:49:03.270 [grpc-nio-worker-ELG-1-4] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x753448b2, L:/192.168.43.63:52035 - R:transcoder.googleapis.com/142.250.192.106:443] OUTBOUND PING: ack=true bytes=0
Exception in thread "main" com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Request contains an invalid argument.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1041)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1215)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:464)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:428)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:461)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.video.transcoder.v1beta1.TranscoderServiceClient.createJob(TranscoderServiceClient.java:237)
		at com.protonn.googletranscoder.CreateJobWithStaticOverlay.createJobWithStaticOverlay(CreateJobWithStaticOverlay.java:125)
		at com.protonn.googletranscoder.CreateJobWithStaticOverlay.main(CreateJobWithStaticOverlay.java:28)
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Request contains an invalid argument.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	... 16 more
13:49:03.301 [grpc-nio-worker-ELG-1-4] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x753448b2, L:/192.168.43.63:52035 - R:transcoder.googleapis.com/142.250.192.106:443] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=0 length=0 bytes=

> Task :CreateJobWithStaticOverlay.main() FAILED
```

**Comment by aditya-protonn** [comment]
I'm just using the transcoder sdk example for java from Google transcoder
website. No code changes from my side

**Comment by Neenu1995** [comment]
Hi,
After looking at the code provided, the location being used is `asia-southeast1`, which is not supported.
Supported regions can be found at https://cloud.google.com/transcoder/docs/concepts/regions
